services:
  prysm:
    image: ghcr.io/openvino/prysm.base-sepolia:latest
    container_name: prysm.base-sepolia
    restart: always
    ports:
      - "4000:4000"
      - "13000:13000"
      - "3500:3500" # optional GRPC gateway
    volumes:
      - prysm_data:/data
      - docker-base-sepolia_jwt_shared:/jwt:ro
    extra_hosts:
      - "reth:172.27.0.2"

volumes:
  prysm_data:
  docker-base-sepolia_jwt_shared:
    external: true

networks:
  base-sepolia-test:
    external: true
