services:
  prysm:
    build: .
    image: ghcr.io/openvino/dappnode-package-prysm.base-sepolia:latest
    container_name: prysm.base-sepolia
    restart: always
    ports:
      - "4000:4000"
      - "13000:13000"
      - "3500:3500" # optional GRPC gateway
    volumes:
      - prysm_data:/data
      - ../docker-base-sepolia/jwt.hex:/data/jwt.hex

volumes:
  prysm_data:

networks:
  default:
    external:
      name: base-sepolia-test

