services:
  reth:
    image: ghcr.io/openvino/base-sepolia:latest
    container_name: reth
    restart: always
    networks:
      - base-sepolia-test
    ports:
      - "8545:8545"
      - "8551:8551"
      - "6060:6060"
      - "30303:30303"
    volumes:
      - jwt_shared:/data/jwt.hex

  prysm:
    image: ghcr.io/openvino/prysm.base-sepolia:latest
    container_name: prysm.base-sepolia
    restart: always
    ports:
      - "4000:4000"
      - "13000:13000"
      - "3500:3500" # optional GRPC gateway
    volumes:
      - prysm_data:/data
      - docker-base-sepolia_jwt_shared:/jwt:ro

volumes:
  jwt_shared:
  prysm_data:

networks:
  base-sepolia-test:
    external: true

